### ISSUE TITLE
scss-lint gem install required on Win 10

### ISSUE THREAD

**Issue by edencorbin** [tarlepp/angular-sailsjs-boilerplate#110]
This is really more of a comment then an issue, I'm sure it can be rapidly closed. In working with this repo on Windows 10, after running npm install in root and frontend/backend directories, the frontend side gulp serve would result in an error regarding scss-lint command not existing. Running a gem install scss-lint in the frontend folder fixed this and I'm up and running, quite excited to check out the package. Also of note, npm start does not seem to work from the root, however separate console windows from frontend/backend with gulp serve / sails lift works great. I thought I should report this in case a small update to the readme or configuration could help resolve these issues quicker for new users.

**Comment by tarlepp** [comment]
Could you make PR to README.md about this?

**Comment by edencorbin** [comment]
Sure thing! Preparing this now.
