### ISSUE TITLE
angularSails sending __getcookie to http://localhost:1337 in production

### ISSUE THREAD

**Issue by beaverusiv** [tarlepp/angular-sailsjs-boilerplate#117]
I have deployed a project based on this repository but angularSails is trying to `GET http://localhost:1337/__getcookie` when it should be trying to `GET https://api.productionsite.co.nz/__getcookie`.

Is there a way to set this as an option in the app, currently it is hardcoded to localhost in ngsails.io.js.

**Comment by beaverusiv** [comment]
Erm, my fault. I had run `gulp dist` _before_ setting the URL in @@backendUrl.

**Comment by tarlepp** [comment]
Just want to be sure that you change that in ```https://github.com/tarlepp/angular-sailsjs-boilerplate-frontend/tree/master/config``` there and not directly in your ```index.html```.

**Comment by beaverusiv** [comment]
Yes `frontend/config/config.json`.
