### ISSUE TITLE
Error login outside localhost

### ISSUE THREAD

**Issue by jjgonver** [tarlepp/angular-sailsjs-boilerplate#122]
Hola. 
I allways test this framework in my PC and login ok with localhost:3001 but when I try to test how It is look like from my smart phone in my local network I can not login.

The next error appear:

'Unknown HTTP status '0', what is this? (HTTP status 0)'

What's happening? Thanks

**Comment by tarlepp** [comment]
Are you absolutely sure that your smartphone has access to that sails backend?

**Comment by jjgonver** [comment]
Yes. The homepage load in the phone screen. Now I test from a laptop in the local network too and the same error appear.

**Comment by tarlepp** [comment]
the homepage is different thing that actual sails backend url, what I was asking. So what is your backendUrl setting in your config.json?

**Comment by tarlepp** [comment]
And make sure that your sails is running on that address...

**Comment by jjgonver** [comment]
Now I don't have config.json. At this moment I continue with the default config_example.json
For the developement enviroment I have in my PC 2 command sesion, one with 'sails lift' for the backend and the other with 'gulp serve' for the frontend, both in the same pc.

For the error of this test I try from another machine in the local network to navigate to the IP of the developement machine with ':3001' at the end.

**Comment by tarlepp** [comment]
....

So your frontend thinks that sails backend is running on ```http://localhost:1337```, so eg. in your smartphone that tries to use your smartphone... Did you read the installation instructions, which explains all what you _need_ to do...

**Comment by jjgonver** [comment]
Ok. Now I understand the problem.

Thanks a lot for your help.

**Comment by tarlepp** [comment]
So issue solved?

**Comment by jjgonver** [comment]
Yes. Solved!
Thanks again.

**Comment by tarlepp** [comment]
then it would be nice to close these issues...
