### ISSUE TITLE
Upload files to AWS S3

### ISSUE THREAD

**Issue by jjgonver** [tarlepp/angular-sailsjs-boilerplate#124]
Hi.
I need to upload files (photo) to AWS S3 and the URL to this file in S3 store it in a photo field in my DB.
Do you know the best way to do it? or Do you know a good tutorial?
Thanks in advance.

**Comment by tarlepp** [comment]
This isn't issue about boilerplate. It's more generic question.

http://sailsjs.org/documentation/concepts/file-uploads/uploading-to-s-3 is the first hit that I got.
