### ISSUE TITLE
How to manage delete cascading 

### ISSUE THREAD

**Issue by jjgonver** [tarlepp/angular-sailsjs-boilerplate#126]
Hi. How can I manage to delete cascading in your boilerplate? For example:
I have 3 model Survey, Answer and Vote. A Survey has N Answer and an Answer has N Vote.
Then, when I delete a Survey (SurveyModel.delete($scope.survey.id).them(...)), I want to delete all the answer of this Survey, and all the Vote of those Answer.

Thanks in advance.

**Comment by tarlepp** [comment]
Sails.js itself doesn't support cascade delete but you can manage that part by yourself eg. http://stackoverflow.com/questions/22462065/sails-js-waterline-orm-removing-data-from-multiply-models

**Comment by jjgonver** [comment]
Well. Before I put my question casually I had read that question in stackoverflow. My doubt was that how to make delete cascading in your frontend with the same syntax. For example:

```
        // Scope function to delete Survey
        $scope.deleteSurvey = function deleteSurvey() {
          SurveyModel
            .delete($scope.survey.id)
            .then(
              function onSuccess() {
                //After delete a Survey we must delete their Answer
                AnswerModel
                .delete({survey: $scope.survey.id})
                .then(
                  function onSuccess(result) {
                    answersId = _.map(result, function(answers) {return answers.id;});
                    VoteModel
                    .delete({answer: answersId})
                  }
                )
                MessageService.success('Survey "' + $scope.survey.question + '" delete.');

                $state.go('survey.dashboard');
              }
            )
          ;
        };
```

Does this code make sense? Should this code work?
A lot of thanks for your help and your patience.

**Comment by tarlepp** [comment]
Personally I would do this all logic on backend side and not in the frontend side code. Eg you could use model lifecycle callbacks to handle all those cascade deletes http://sailsjs.org/documentation/concepts/models-and-orm/lifecycle-callbacks

**Comment by jjgonver** [comment]
Thanks for show me the correct way.

**Comment by jjgonver** [comment]
By the way. I made you a private question by Gitter - Sails (@jjgonver) that is not an issue about your boilerplate. Would you be so kind as to take a look? Thanks
