### ISSUE TITLE
Request: Steps to deploy to Heroku

### ISSUE THREAD

**Issue by anupsarode** [tarlepp/angular-sailsjs-boilerplate#26]
Hello,

Tarlepp, you're doing a wonderful job by posting this boiler plate code. I was able to deploy the backend part to Heroku properly. But I'm not sure how the frontend can be properly deployed on Heroku. I'm relatively new to Gulp. If you can help with some steps to deploy to Heroku, that will be great.

Warm Regards!

**Comment by tarlepp** [comment]
@anupsarode Did you get Heroku deplo working? If yes, could you provide PR that contains detailed information about that?

**Comment by tarlepp** [comment]
Any updates?

**Comment by tarlepp** [comment]
@anupsarode ^up

**Comment by anupsarode** [comment]
Hello,

I got it up and running on Heroku. Following are the steps.

1) In the sails project, install forever module

$ sudo npm install forever --save

2) Create a Procfile in the projects root folder with following copy in it

web: ./node_modules/.bin/forever app.js

3) Create an App in Heroku Dashboard and Login to Heroku in Terminal

$ heroku login

4) Clone the repo to the local machine

$ heroku git:clone -a <AppName>
$ cd <AppName>

5) Deploy the changes from local machine to Heroku

$ git add .
$ git commit -am "Initial Commit"
$ git push heroku master

6) Test

$ heroku open

**Comment by tarlepp** [comment]
@anupsarode thanks for the info, closing this now.
