### ISSUE TITLE
Consider switching ModelFactory over to prototypes

### ISSUE THREAD

**Issue by ProLoser** [tarlepp/angular-sailsjs-boilerplate#38]
I used Coffeescript specifically so I could do a sort of class structure where I have a base model class that all other models extend from. Essentially this simply uses the javascript prototype system. It makes for quite elegant code.

**Comment by tarlepp** [comment]
@ProLoser I did some refactor job for that service, but I'm not sure if this is what you ment. Feel free to comment.
