### ISSUE TITLE
Compatibility with IE

### ISSUE THREAD

**Issue by Knps** [tarlepp/angular-sailsjs-boilerplate#43]
When I run app example, once logged, I'm tried to access examples page, but it's don't work. Of corse, it's work with firfox, chrome ...

**Comment by tarlepp** [comment]
Updated to sails 0.11.0 couple of days ago, is this issue still open?

**Comment by tarlepp** [comment]
Seems like angularSails doesn't have latest version on bower yet, I'll have to wait for that to fix this.

**Comment by siready** [comment]
I can confirm this, they have to release new version. Using master branch version works fine.

**Comment by tarlepp** [comment]
Personally I don't like to use 'master' branches of 3rd party libraries. I hope that those Balderdashy guys make a real release soon.
