### ISSUE TITLE
Relocate AccessLevels and BackendConfig into Auth

### ISSUE THREAD

**Issue by ProLoser** [tarlepp/angular-sailsjs-boilerplate#49]
You're mixing up how you choose to break down your app. On one hand you have a folder for authentication-specific logic, and on the other hand you have a location for the type of variable something is. Honestly, I think you should relocate backendconfig and accesslevels (or maybe just the latter) to your auth module.

I also would recommend putting that index.html io.sails.url tweak into your backendconfig file and not making it JUST the constant, but also handle properly configuring the backend.

**Comment by tarlepp** [comment]
closing this
