### ISSUE TITLE
DataService could be dropped and an injector could be used instead

### ISSUE THREAD

**Issue by ProLoser** [tarlepp/angular-sailsjs-boilerplate#51]
I don't really like that the $sailsSocket service is being needlessly wrapped and obfuscated just so you can prefix the endpoint urls. This is exactly what interceptors are for, and since BackendConfig is a constant, you can access it at config time instead of just runtime, further rendering this wrapper superfluous.

**Comment by tarlepp** [comment]
Basically not going to drop this, reason if $sailsSocket is replaced with another one so on that case i just need to refactor this DataService.
