### ISSUE TITLE
Sockets can`t recreate the session

### ISSUE THREAD

**Issue by thiagof** [tarlepp/angular-sailsjs-boilerplate#58]
Sometimes on my development process, `sails` session run out and the app gets broken. Sockets.io do not recreate sessions, so every socket connection get *unauthenticated* in sails side. This behavior is not seen by the app which do nothing.

The problem is better documented on this [comments](https://github.com/balderdashy/sails/issues/2263#issuecomment-64967274)

I bring the problem to **angular boilerplate** because the app architecture collaborate for the issue, as sails server is reached only be sockets.

I`ll try to match the failed connect within interceptors, but not sure yet how to detect it. Maybe a fix  for `AuthInterceptor`.

**Comment by tarlepp** [comment]
This should be fixed with current version of boilerplate, thanks to sails 0.11.0.
