### ISSUE TITLE
Barrels with manual associations is unreliable

### ISSUE THREAD

**Issue by caasjj** [tarlepp/angular-sailsjs-boilerplate#59]
Auth testing fails sporadically, caused by https://github.com/bredikhin/barrels/issues/17.

This is possibly caused by barrels not creating instances of a model sequentially, hence users get different ID's on different startups, and the association gets criss crossed between users - haven't had a chance to go through their source yet.

**Comment by tarlepp** [comment]
Hmm, seems like this is working ok. Closing this one for now, re-open if this occurs again.
