### ISSUE TITLE
ERROR npm install

### ISSUE THREAD

**Issue by ilyago** [tarlepp/angular-sailsjs-boilerplate#62]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose install where, deps [ 'D:\\PROJECTS\\angular-sailsjs-boilerplate', [] ]
6 verbose install where, peers [ 'D:\\PROJECTS\\angular-sailsjs-boilerplate', [] ]
7 info preinstall angular-sailsjs-boilerplate@1.0.0
8 silly install resolved []
9 info build D:\PROJECTS\angular-sailsjs-boilerplate
10 verbose linkStuff [ false, false, false, 'D:\\PROJECTS' ]
11 info linkStuff angular-sailsjs-boilerplate@1.0.0
12 verbose linkBins angular-sailsjs-boilerplate@1.0.0
13 verbose linkMans angular-sailsjs-boilerplate@1.0.0
14 verbose rebuildBundles angular-sailsjs-boilerplate@1.0.0
15 info install angular-sailsjs-boilerplate@1.0.0
16 verbose unsafe-perm in lifecycle true
17 info angular-sailsjs-boilerplate@1.0.0 Failed to exec install script
18 verbose stack Error: angular-sailsjs-boilerplate@1.0.0 install: `cd backend && npm install && cd ../frontend && npm install`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
18 verbose stack     at EventEmitter.emit (events.js:110:17)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
18 verbose stack     at ChildProcess.emit (events.js:110:17)
18 verbose stack     at maybeClose (child_process.js:1008:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
19 verbose pkgid angular-sailsjs-boilerplate@1.0.0
20 verbose cwd D:\PROJECTS\angular-sailsjs-boilerplate
21 error Windows_NT 6.3.9600
22 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
23 error node v0.12.0
24 error npm  v2.5.1
25 error code ELIFECYCLE
26 error angular-sailsjs-boilerplate@1.0.0 install: `cd backend && npm install && cd ../frontend && npm install`
26 error Exit status 1
27 error Failed at the angular-sailsjs-boilerplate@1.0.0 install script 'cd backend && npm install && cd ../frontend && npm install'.
27 error This is most likely a problem with the angular-sailsjs-boilerplate package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     cd backend && npm install && cd ../frontend && npm install
27 error You can get their info via:
27 error     npm owner ls angular-sailsjs-boilerplate
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by ilyago** [comment]
you have't mentioned in requirements! got Git installed.

**Comment by ilyago** [comment]
ageing require python

**Comment by ilyago** [comment]
this is getting on my nerves!

D:\PROJECTS\angular-sailsjs-boilerplate\frontend>npm install
npm WARN package.json karma-chrome-launcher@0.1.7 No README data
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm WARN package.json karma-mocha@0.1.10 No README data
-
> node-sass@0.9.6 install D:\PROJECTS\angular-sailsjs-boilerplate\frontend\node_modules\gulp-sass\node_modules\node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.

D:\PROJECTS\angular-sailsjs-boilerplate\frontend\node_modules\gulp-sass\node_modules\node-sass>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platf
orm for project 'binding.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to
 build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project
. [D:\PROJECTS\angular-sailsjs-boilerplate\frontend\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\PROJECTS\angular-sailsjs-boilerplate\frontend\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\PROJECTS\angular-sailsjs-boilerplate\frontend\npm-debug.log

D:\PROJECTS\angular-sailsjs-boilerplate\frontend>

**Comment by tarlepp** [comment]
Sorry I don't use Windows for dev, so I haven't tested installation to Windows at anypoint. So basically there isn't dev support for Windows.

Seems like actual error is referensing to ```C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe```, you could start there.

Personally I recommend that you install linux environment to vm (eg. virtualbox) and start there.

**Comment by siready** [comment]
See answers here to resolve the issue.
http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012?answertab=votes#tab-top

Once configured, it works without any problem.

**Comment by tarlepp** [comment]
And @siready is for the help, nice! @ilyago can you confirm that everything works?

**Comment by ilyago** [comment]
i have installed on virtual box it works great thanks

**Comment by tarlepp** [comment]
oh, great!

**Comment by tarlepp** [comment]
Oh, great!
