### ISSUE TITLE
Compatible with phonegap?

### ISSUE THREAD

**Issue by Mayayushi** [tarlepp/angular-sailsjs-boilerplate#65]
Thanks a lot Tarlepp for sharing!! :)
I'm relatively new to Sails and Angular, and trying to create a hybrid app that I can use with phonegap and put on the app store. The documentation around is lacking, and a lot of people seem to be confused about how they all fit together as well. Your solution could be a huge help!!
I just wanted to ask a couple of questions: Is this readily usable with phonegap, (as in you just use the frontend/dist folder)? And in this case would all the functionality (authentication, websockets, etc.. ) still work?

**Comment by tarlepp** [comment]
First of all, thanks for positive feedback! It's always nice to hear that this really help.

I haven't tried phonegap with frontend code, so I cannot be sure if that works or not. But basically after you have make ```dist``` code it should work just standalone, and if I remember right phonegap consumes basic ```html+css+js``` so you should be ok there (I haven't used phonegap in years, maybe I should take another look at somepoint).

If you get frontend code work with phonegap it would be very nice, if you could provide some pointers about that.

**Comment by thesabbir** [comment]
@tarlepp I using ionic as frontend for my. I was wondering if I could only use your backend codes.

**Comment by tarlepp** [comment]
I don't see any reason why you cannot use backend side code for your app. Closing this for now.
