### ISSUE TITLE
Full of errors when intializing, and index page on front end wont load

### ISSUE THREAD

**Issue by nigel-dewar** [tarlepp/angular-sailsjs-boilerplate#81]
Gday mate, I appreciate all the work you put into this. I'm going to rebuild this project ( bug free ) because I think your idea is really great.

Cheers

**Comment by tarlepp** [comment]
What kind of errors you get? And please make PR of all fixes.

**Comment by nigel-dewar** [comment]
Hi Tarmo,

 

I got a heap a bunch of errors popped up when running npm install ( at the tail end of the install process ). Sails runs fine. But when running the frontend I get quite a few errors and the page loads, but then with nothing on it, except some strange symbol in top left corner.

 

I can detail these later, but I’ll do some troubleshooting first. I’ve been through this before even using Microsoft github projects. I found the best way is to completely build a fresh project from scratch, using all the same ideas and tools as the original project, and this helps narrow down the issues, be it on my specific machine (environment), versions differences, or actual errors in the code. Tbh it can be a mix of all of these.

 

I’ll close this issue ( because its not an issue until proved an issue ), and I’ll come back to you with some detailed info.

 

Like I said though, I think what you’ve done is really great, and I think sails/angular boilerplate project is totally killer!

 

When I send you my notes, I’ll post through the code for accessing Microsoft Azure AD ( passport Azure ), accessing all of the Office 365 APIs, including SharePoint, and a few other things like using SQL server for instance. I recently worked through this issue with a guy at MS, where they had errors in their code for using node with O365, especially around sharepoint. Although the average developer may not be interested in this, anyone in business development definitely would be, and I think sailsjs really is business class backend tech. I’d also like to add ( with your permission of course ), examples for accessing Google API’s, making Twitter tweets etc. Basically enhancements to your boilerplate that really show the developer how you can use the boilerplate to produce kick ass enterprise cloud apps. Its something missing from so many projects. 

 

I’ve been hunting around for something I’d call ‘The Ultimate BoilerPlate’, especially for enterprise developers faced with the typical Microsoft stuff so common today, and I’d love to help developers start phasing off of .net, and onto node. I think sails has gotta be one the best steps forwards as far as providing that enterprise framework for doing so, and the coupling with angular (slush-angular) just makes that all the more sweeter.

 

It would just be nice to have a boilerplate that you run up no matter what project your starting. Be it a small, fun app for your mates, some killer new startup project for IOT, an app for remotely controlling your drone or robot, or home automation , or a corporate app where your having to deal with AD, SQL servers, and MS or Google cloud data sources. No matter the case, a flexible, customizable boilerplate that gets you going as fast as you can write ‘git clone ultimateboilerplate.git’ would be awesome.
