### ISSUE TITLE
Route to check if token is valid

### ISSUE THREAD

**Issue by taylorjames** [tarlepp/angular-sailsjs-boilerplate#84]
Does this framework currently have a route that will check a token and pass back the session user if it is valid? If not can this easily be done?

I am setting this backend up with a react/fluxible front-end. I have the login working and am storing the token locally however the front-end needs to know weather or not there is currently a valid session and if so what user that session belongs to. That way if the page is refreshed no log-in states are changed.

**Comment by tarlepp** [comment]
Actually token validation is done in backend when user is fetching some data that needs some privileges. And generally old-fashion way sessions (cookie based) are disabled.

You could make same kind of auth checking that I'm using within frontend side:

1) You make login and you get JWT and user data object which contains all user specified generic data
2) Store those to your browser local storage
3) Make a request interceptor which will add JWT to each request headers [code](https://github.com/tarlepp/angular-sailsjs-boilerplate/blob/master/frontend%2Fsrc%2Fapp%2Fcore%2Finterceptors%2FAuthInterceptor.js#L27)
4) And whenever server respons with status code 401 (Unauthorized) reset local storage and redirect user back to login screen [code](https://github.com/tarlepp/angular-sailsjs-boilerplate/blob/master/frontend%2Fsrc%2Fapp%2Fcore%2Finterceptors%2FAuthInterceptor.js#L59)

Hope this helps.

**Comment by taylorjames** [comment]
Good idea, ill try it out. 

Thanks!

**Comment by Tenkir** [comment]
Is this not in the boilerplate code? I have this written already and can open a PR to add it if not.

**Comment by tarlepp** [comment]
Yeah this logic is already on the "boilerplate" code and PR #89 improves this logic. Closing this one, feel free to open it again if you have more questions.
