### ISSUE TITLE
Loading jQuery before angular

### ISSUE THREAD

**Issue by Hanifb** [tarlepp/angular-sailsjs-boilerplate#96]
First of all, great boilerplate.
Im using jquery.sortable in my application and it requires that jquery is loaded before angular, but i cant seem to make gulp do this, can you give any hints?

**Comment by tarlepp** [comment]
Hi,

Frontend uses ```bower``` to handle 3rd party libraries. So basically you need to use ```bower install <yourpackage> --save``` command to install any 3rd party library that you need. And then if you need to change the load order of those see your ```bower.json``` file and modify it.

**Comment by Hanifb** [comment]
Thank you!

**Comment by Hanifb** [comment]
@tarlepp Thank you!
